export enum SupportedLanguage {
  ARABIC = 'Arabic',
  CHINESE = 'Chinese',
  DANISH = 'Danish',
  DUTCH = 'Dutch',
  FILIPINO = 'Filipino',
  FINNISH = 'Finnish',
  FRENCH = 'French',
  GERMAN = 'German',
  GREEK = 'Greek',
  ICELANDIC = 'Icelandic',
  ITALIAN = 'Italian',
  JAPANESE = 'Japanese',
  NORWEGIAN = 'Norwegian',
  PORTUGUESE = 'Portuguese',
  RUSSIAN = 'Russian',
  SPANISH = 'Spanish',
  TURKISH = 'Turkish',
  UKRAINIAN = 'Ukrainian',
}
